const themes=[
 ['Mesversário','Mais procurado','Cenários delicados e personalizados para cada mês.'],['Aniversário','Celebre','Ensaios temáticos para transformar a data em lembrança.'],['Família','Afeto','Retratos naturais com estética de estúdio.'],['Pets','Favoritos','Retratos especiais do seu melhor amigo.'],['Profissional','Premium','Imagem profissional sem precisar ir ao estúdio.'],['Datas especiais','Sazonal','Natal, Dia das Mães, Páscoa e muito mais.']
];
const prices=[['1 foto','R$ 17'],['2 fotos','R$ 25'],['3 fotos','R$ 35']];
let chosenTheme='Mesversário', chosenPackage='1 foto';
const cfg=window.STUDIO_CONFIG||{};
document.querySelectorAll('[data-instagram]').forEach(a=>a.href=cfg.instagram||'#');document.querySelectorAll('[data-whatsapp]').forEach(a=>a.href=cfg.whatsapp||'#');
const themesEl=document.querySelector('#themes');themes.forEach(([name,tag,desc])=>{const b=document.createElement('button');b.className='card'+(name===chosenTheme?' active':'');b.innerHTML=`<span>${tag}</span><h3>${name}</h3><p>${desc}</p><b>Ver modelos →</b>`;b.onclick=()=>{chosenTheme=name;document.querySelector('#chosenTheme').textContent=name;[...themesEl.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')};themesEl.appendChild(b)});
const pricesEl=document.querySelector('#prices');function syncPrice(){document.querySelector('#priceConfirm').innerHTML=`Ao gerar, você confirma que viu o preço do pacote selecionado: <b>${chosenPackage}</b>.`};prices.forEach(([name,price])=>{const b=document.createElement('button');b.className=name===chosenPackage?'selected':'';b.innerHTML=`<span>${name}</span><strong>${price}</strong><small>até 2 pessoas</small>`;b.onclick=()=>{chosenPackage=name;[...pricesEl.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');syncPrice()};pricesEl.appendChild(b)});syncPrice();
document.querySelector('#generate').onclick=async()=>{const input=document.querySelector('#photo');if(!input.files[0])return alert('Envie uma foto primeiro.');const btn=document.querySelector('#generate');btn.disabled=true;btn.textContent='CRIANDO SUA PRÉVIA...';try{const fd=new FormData();fd.append('image',input.files[0]);fd.append('theme',chosenTheme);fd.append('package',chosenPackage);const r=await fetch(cfg.apiEndpoint||'/generate',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível gerar a prévia.');document.querySelector('#preview').innerHTML=`<img src="${j.preview}" alt="Prévia protegida"><div class="decision"><a class="cta" target="_blank" href="${cfg.kiwifyCheckout||'#'}">AMEI! QUERO DESBLOQUEAR</a><a class="ghost" target="_blank" href="${cfg.whatsapp||'#'}">Não gostei — falar no WhatsApp</a></div>`}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='GERAR MINHA PRÉVIA'}};
